#!/bin/bash

ZEND_LICENSE_ORDER=cloudfoundry
ZEND_LICENSE_KEY=1OVO7341801G21B08FD927480286D7CA
ZS_MANAGE=/usr/local/zend/bin/zs-manage
ZS_ADMIN_PASSWORD=123456
HOSTNAME=`hostname`
APP_UNIQUE_NAME=$HOSTNAME
APP_IP=`/sbin/ifconfig eth0| grep 'inet addr:' | awk {'print $2'}| cut -d ':' -f 2`

echo "api_key:"
cat /root/api_key
echo "zend_cluster.sh:"
cat /root/zend_cluster.sh

service zend-server start
WEB_API_KEY=`cut -s -f 1 /root/api_key`
WEB_API_KEY_HASH=`cut -s -f 2 /root/api_key`
eval `cat /root/zend_cluster.sh`
if [ -z $WEB_API_KEY ]; then
echo "Bootstrapping single"
$ZS_MANAGE bootstrap-single-server -p $ZS_ADMIN_PASSWORD -a 'TRUE' -o $ZEND_LICENSE_ORDER -l $ZEND_LICENSE_KEY | head -1 > /root/api_key

WEB_API_KEY=`cut -s -f 1 /root/api_key`
WEB_API_KEY_HASH=`cut -s -f 2 /root/api_key`

fi
if [[ -n $MYSQL_HOSTNAME && -n $MYSQL_PORT && -n $MYSQL_USERNAME && -n $MYSQL_PASSWORD && -n $MYSQL_DBNAME ]]; then
echo "add to cluster"
echo "$ZS_MANAGE server-add-to-cluster -n $APP_UNIQUE_NAME -i $APP_IP -o $MYSQL_HOSTNAME:$MYSQL_PORT -u $MYSQL_USERNAME -p $MYSQL_PASSWORD -d $MYSQL_DBNAME -N $WEB_API_KEY -K $WEB_API_KEY_HASH -s"
$ZS_MANAGE server-add-to-cluster -n $APP_UNIQUE_NAME -i $APP_IP -o $MYSQL_HOSTNAME:$MYSQL_PORT -u $MYSQL_USERNAME -p $MYSQL_PASSWORD -d $MYSQL_DBNAME -N $WEB_API_KEY -K $WEB_API_KEY_HASH -s| sed -e 's/ //g' > /root/zend_cluster.sh
echo "MYSQL_HOSTNAME=$MYSQL_HOSTNAME
MYSQL_PORT=$MYSQL_PORT
MYSQL_USERNAME=$MYSQL_USERNAME
MYSQL_PASSWORD=$MYSQL_PASSWORD
MYSQL_DBNAME=$MYSQL_DBNAME" >> /root/zend_cluster.sh

eval `cat /root/zend_cluster.sh`
$ZS_MANAGE store-directive -d 'session.save_handler' -v 'cluster' -N $WEB_API_KEY -K $WEB_API_KEY_HASH

echo "restarting ZS"
$ZS_MANAGE restart-php -p -N $WEB_API_KEY -K $WEB_API_KEY_HASH

echo "zend_cluster.sh:"
cat /root/zend_cluster.sh

echo "nothing $MYSQL_HOSTNAME $MYSQL_PORT $MYSQL_USERNAME $MYSQL_PASSWORD $MYSQL_DBNAME $NODE_ID $WEB_API_KEY $WEB_API_KEY_HASH"
exec /usr/local/bin/nothing $MYSQL_HOSTNAME $MYSQL_PORT $MYSQL_USERNAME $MYSQL_PASSWORD $MYSQL_DBNAME $NODE_ID $WEB_API_KEY $WEB_API_KEY_HASH
fi

echo "restarting ZS"
$ZS_MANAGE restart-php -p -N $WEB_API_KEY -K $WEB_API_KEY_HASH
echo "nothing"
exec /usr/local/bin/nothing
